data_root_dir: /checkpoint/ocp/shared
run_dir: /checkpoint/ocp/shared/uma
account: ocp
qos: h100_ocp_high
mode: SLURM
device: CUDA
ranks_per_node: 8
dataloader_workers: 8
debug: False
mem_gb: 0
cpus_per_task: 24
mp_start_method: fork
